### PR TITLE
Clean up after the unit tests by removing the files created

### PR DESCRIPTION
**Pull request by stscirij**

### CODE REVIEW

**Comment by stscirij** [comment]
This should fix the Jenkins errors that occur when a file cannot be found when running the unit tests

**Comment by zacharyburnett** [comment]
I would recommend using the `tmp_path` fixture from `pytest`; I made a PR to pull into this branch: https://github.com/stscirij/calcos/pull/4

**Comment by stscirij** [comment]
> I would recommend using the `tmp_path` fixture from `pytest`; I made a PR to pull into this branch: [stscirij#4](https://github.com/stscirij/calcos/pull/4)

Thanks! - I tried this out and got an error, I think I'd rather stick to my perhaps less Pythonic but cleaner implementation

**Review by stenhasselquist — APPROVED** [review]
Looks good

**Pull request merged**
