### PR TITLE
Changed ACCUM FITS file creation 

### PR DESCRIPTION
**Pull request by jotaylor**
Uses update mode instead of append mode, fixes issue #25

### CODE REVIEW

**Comment by Rplesha** [comment]
@jotaylor Can you merge this fix with the latest version of CalCOS so we can properly test this fix? The latest should be version 3.3.4.

**Comment by jotaylor** [comment]
Done! 👍

**Comment by jamienoss** [comment]
>@jotaylor Can you merge this fix with the latest version of CalCOS so we can properly test this fix? The latest should be version 3.3.4.

Hey guys, just a quick tip. It's normally a good idea not to merge untested branches onto master. The better approach would be to rebase this branch with spacetelescope:master and then just test this branch. This branch can always be pushed to spacetelescope/calcos if convenient visibility is desired. Anyhoo, just a friendly tip. Have fun!

**Comment by jamienoss** [comment]
Hey guys, just a friendly tip, it's better to rebase than merge. Have fun!

**Comment by jotaylor** [comment]
@jamienoss oops, thanks for the heads up! Fixed it up with a bit of git magic 😇

**Pull request merged**
